### ISSUE TITLE
QRCode printing the code type

### ISSUE THREAD

**Issue by ezequiel88** [NielsLeenheer/EscPosEncoder#19]
Above QRCode is printing the code type. How to remove this number?

![image](https://user-images.githubusercontent.com/25781425/66432664-fbf5e900-e9f4-11e9-8ded-87104b1f8c14.png)

**Comment by DzCorps** [comment]
Hello, i don't have this problem with a rawBt printer, but i have a random behaviour, qrCode is printed twice !!

**Comment by lovelyelfpop** [comment]
I have this problem with two printers, too.
And one printer doesnot print the qrcode.

**Comment by NielsLeenheer** [comment]
The problem is probably the printer. But I'll see if I can create a workaround.

The "1" you are seeing is most likely the number of the QR code type. Your printer probably does not support setting different QR code types and as a result it will ignore the command we send to change the QR code type and print out the parameters of that command.

**Comment by aprakasa** [comment]
Is there any hotfix for this?
