### ISSUE TITLE
Image print issue

### ISSUE THREAD

**Issue by AlessandraB19** [NielsLeenheer/EscPosEncoder#50]
Hello, I'm trying to print an image in my ionic app. 
    var img = new Image();
    img.src = 'https://sguru.org/wp-content/uploads/2018/02/facebook-logo-jpg-facebook-logo-1.jpg';
    .image(img, 40, 40, 'threshold')
This is part of the code, but when I try to print there isn't any image on the receipt, it's all blank and in the ispection there aren't any errors. Can you give me support on this problem? Thank you.

**Comment by NielsLeenheer** [comment]
It's hard to give support on this issues as there is very little information about how you are using the library. But what you can try to look at is whether or not the image is loaded using the browser's network dev tools. If not, that is something you could try to fix. 

And one other possible area is CORS. If you are loading an image from a different domain than where the app is running, you might encounter issues. If you have control over that other domain you could add CORS headers to prevent this issues. Otherwise use a CORS proxy on your app's domain or simply move the images over to your app's domain. 

More info can be found here:
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
